 * Running on http://0.0.0.0:7001/ (Press CTRL+C to quit)
 * Restarting with stat
127.0.0.1 - - [11/Jul/2015 09:44:55] "GET /gds/produce/datamodule/list? HTTP/1.0" 404 -
127.0.0.1 - - [11/Jul/2015 09:45:03] "GET /gds/? HTTP/1.0" 404 -
127.0.0.1 - - [11/Jul/2015 09:45:08] "GET /gds/produce? HTTP/1.0" 404 -
 * Detected change in '/Users/haokuan/workspace/wecatch/wecatch-grab/gds/blueprints/monitor/views.py', reloading
use mysql.connector.
 * Restarting with stat
 * Detected change in '/Users/haokuan/workspace/wecatch/wecatch-grab/gds/blueprints/monitor/views.py', reloading
use mysql.connector.
 * Restarting with stat
 * Detected change in '/Users/haokuan/workspace/wecatch/wecatch-grab/gds/blueprints/produce/views.py', reloading
use mysql.connector.
 * Restarting with stat
use mysql.connector.
Traceback (most recent call last):
  File "manager.py", line 5, in <module>
    from views import app
  File "/Users/haokuan/workspace/wecatch/wecatch-grab/gds/views.py", line 12, in <module>
    from blueprints.produce.views import produce
  File "/Users/haokuan/workspace/wecatch/wecatch-grab/gds/blueprints/produce/views.py", line 7, in <module>
    @monitor.route('/datamodule/list', methods=['GET'])
NameError: name 'monitor' is not defined
use mysql.connector.
